copyright = "© 2021 Daniel F. Dickinson"
homepage = "https://hugo-dfd-demo-site-theme.wildtechgarden.ca/"
description = "Hugo theme module for demo sites"
enableGitInfo = true
defaultContentLanguage = "en"

# See https://gohugo.io/content-management/multilingual/
# and https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/
[languages]
  [languages.en]
    languageName = ":en:"
    languageAltTitle = "English"
    title = "DFD Demo Site Theme"
    weight = 1

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/"

  [[author.authors]]
    name = "Daniel F. Dickinson"
    homepage = "https://www.danielfdickinson.ca/"

[module]
  [[module.imports]]
    path = "github.com/danielfdickinson/hugo-dfd-microformats"
  [[module.imports]]
    path = "github.com/danielfdickinson/hugo-debug-tables"
