name = "Hugo DFD Demo Site Theme"
license = "MIT"
licenselink = "https://github.com/danielfdickinson/hugo-dfd-demo-site-theme/blob/master/LICENSE"
description = "Theme for Daniel F. Dickinson's demo sites"
homepage = "http://hugo-dfd-demo-site-theme.wildtechgarden.ca/"
tags = ["demo","minimal","light","minimalist","fast"]
features = ["light","fast","debug tables","minimalist"]
min_version = "0.81.0"
extended = false
summaryLength = "30"

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/"
  copyright = "© 2021 Daniel F. Dickinson"
