baseURL = "https://example.com/"
copyright = "© 2021 Daniel F. Dickinson"
description = "Theme for Daniel F. Dickinson's demo sites"
homepage = "https://hugo-dfd-site-theme.wildtechgarden.ca/"
enableGitInfo = true
enableRobotsTXT = true
defaultContentLanguage = "en"

[params]
  mainSections = ["post","docs"]

[languages]
  [languages.en]
    languageName = ":en:"
    languageAltTitle = "English"
    title = "DFD Demo Site Theme"
    weight = 1
    
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/"

  [[author.authors]]
    name = "Daniel F. Dickinson"
    homepage = "https://www.danielfdickinson.ca/"

[taxonomies]
  category = "categories"
  tag = "tags"

[frontmatter]
  lastmod = ["lastmod",":git",":fileModTime","date","publishDate"]
  date = ["date","publishDate","lastmod",":git",":fileModTime"]
  publishDate = ["publishDate","date","lastmod",":git",":fileModTime"]

[privacy]

  [privacy.vimeo]
    disabled = true

  [privacy.twitter]
    disabled = true

  [privacy.instagram]
    disabled = true

  [privacy.youtube]
    disabled = true

[module]
  [[module.imports]]
    path = "github.com/danielfdickinson/hugo-dfd-demo-site-theme"

    [[module.imports.mounts]]
      source = "content"
      target = "content"

    [[module.imports.mounts]]
      source = "static"
      target = "static"

    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "data"
      target = "data"

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/README-demo-site-theme.md"

    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"
